USE jugos;

CREATE TABLE TBCLIENTES(
DNI VARCHAR(20),
NOMBRE VARCHAR(150),
DIRECCION1 VARCHAR(150),
DIRECCION2 VARCHAR(150),
BARRIO VARCHAR(50),
CIUDAD VARCHAR(50),
ESTADO VARCHAR(50),
CP VARCHAR(10),
EDAD SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT(1)
);

CREATE TABLE TBPRODUCTOS(
PRODUCTO VARCHAR(150),
NOMBRE VARCHAR(150),
ENVASE VARCHAR(50),
VOLUMEN DECIMAL(5,2),
SABOR VARCHAR(50),
PRECIO DECIMAL(5,2)
);